apiVersion: v1
kind: Service
metadata:
  name: mymavenapp
  labels:
    app: mymavenapp
spec:
  type: NodePort
  selector:
    app: mymavenapp
  ports:
    - port: 8081        # Service port
      targetPort: 8080  # Container port (Tomcat)
      protocol: TCP
